site_name: CF Wiki

nav:
    - 主页: index.md
    - 新手: quest.md
    - 系统: System.md
    - A级活动: A_Activity.md
    - B级活动: B_Activity.md
    - C级活动: C_Activity.md
    - 活动配置: Activity.md
    - Inbox: inbox.md

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - zh_CN
    locale: zh_CN

# theme:
#     name: readthedocs
#     highlightjs: true
#     hljs_languages:
#         - zh_CN
#     locale: zh_CN

# site_url: https://xuxiaolei0317.github.io/CF-wiki/