site_name: CF Wiki

nav:
    - 主页: index.md
    - A_Activity: A_Activity.md
    - C_Activity: C_Activity.md
    - 活动配置: Activity.md
    - 系统配置: System.md
    - 新手: quest.md

theme:
    # name: readthedocs
    name: readthedocs
    highlightjs: true
    # hljs_languages: zh_CN
    locale: zh_CN

# site_url: https://gitee.com/xuxiaolei317_admin/cf-wiki/docs/index.md