[
    {text:'login bonus领奖+活动强弹+活动中心活动配置检查、遍历跳转、购买', checked: false, category: '系统', login: 1},
    {text:'社区群跳转', checked: false, category: '系统', login: 1},
    {text:'大厅广告位活动检查+跳转+购买、大厅主题集合及排序检查', checked: false, category: '系统', login: 1},
    {text:'新主题spin、新主题内侧边栏活动检查+跳转', checked: false, category: '系统', login: 1},
    {text:'inbox领奖', checked: false, category: '系统', login: 1},
    {text:'劳工节排行榜结算+奖励发放', checked: false, category: '系统', login: 1},
    {text:'15分钟赛', checked: false, category: '系统', login: 1},
    {text:'商店入场特效+金币购买+spin up购买+hotdeal购买+deal购买', checked: false, category: '系统', login: 1},
    {text:'横竖版MB购买', checked: false, category: '系统', login: 1},
    {text:'bonus games游玩', checked: false, category: '系统', login: 1},
    {text:'邮票玩法开邮票包+灯神小游戏+frenzy spin+浏览邮票+排行榜', checked: false, category: '系统', login: 1},
    {text:'byd开仓库+领取每日奖励+唤起C礼包活动、跳转、购买', checked: false, category: '系统', login: 1},
    {text:'atw开购物袋+浏览shop+浏览排行榜', checked: false, category: '系统', login: 1},
    {text:'mansion建造+浏览', checked: false, category: '系统', login: 1},
    {text:'公会消息浏览+公会任务领奖+发送消息', checked: false, category: '系统', login: 1},
    {text:'inbox检查', checked: false, category: '系统', login: 1},
    {text:'大厅任务集合查看+跳转', checked: false, category: '系统', login: 1},
    {text:'新主题内spin，领取41016活动奖励', checked: false, category: '系统', login: 1},
    {text:'奖励中心蓝刮刮卡+红刮刮卡', checked: false, category: '系统', login: 1},
    {text:'商店入场特效+金币购买+hotdeal购买+deal购买', checked: false, category: '系统', login: 1},
    {text:'横竖版MB购买', checked: false, category: '系统', login: 1},
    {text:'MP等级购买+奖励领取', checked: false, category: '系统', login: 1},
    {text:'奖励中心蓝刮刮卡+红刮刮卡+领取/赠送好友邮票，金币，礼盒', checked: false, category: '系统', login: 1},
    {text:'cash go 登陆领奖+spin+好友+宠物喂养', checked: false, category: '系统', login: 1},
    {text:'daily mission主题内spin+消耗第二货币完成任务领奖', checked: false, category: '系统', login: 1},
    {text:'个人中心更换头像形象+成就系统领奖+更换大厅皮肤', checked: false, category: '系统', login: 1},
    {text:'邮票开包+frenzy spin+灯神游玩+灯神开包', checked: false, category: '系统', login: 1},
    {text:'BYD+开包+C活动查看，跳转，购买，领奖', checked: false, category: '系统', login: 1},
    {text:'ATW开包，收奖，set收奖', checked: false, category: '系统', login: 1},
    {text:'BC刷新，完成任务，任务跳转，领取奖励', checked: false, category: '系统', login: 1},
    {text:'soc小游戏', checked: false, category: '系统', login: 1},
    {text:'使用绿宝石完成任务领奖', checked: false, category: '系统', login: 1},
    {text:'劳工节所有玩法+开卡包+小游戏', checked: false, category: '系统', login: 1},
    {text:'劳工节各个促销跳转+购买', checked: false, category: '系统', login: 1},
    {text:'merge游玩+Bpass收奖+关卡收奖+劳工节pass领奖', checked: false, category: '系统', login: 1},
    {text:'rocket游玩+Bpass收奖+关卡收奖+购买token礼包booster礼包', checked: false, category: '系统', login: 1},
    {text:'journey游玩+Bpass收奖+boss玩法+购买booster1使用', checked: false, category: '系统', login: 1},
    {text:'cash go 登陆领奖，领取好友赠送spin', checked: false, category: '系统', login: 1},
    {text:'10倍spin+建造切场景+偷钱+攻击+喂养+C活动付费', checked: false, category: '系统', login: 1},
    {text:'mansion建造', checked: false, category: '系统', login: 1},
    {text:'公会发消息+查看成员信息+完成公会任务领奖', checked: false, category: '系统', login: 1},
    {text:'成就系统领奖；奖励中心跳转', checked: false, category: '系统', login: 1},
]