[
    {text:'主题所有玩法显示和奖励正常', checked: false, category: '主题' },
    {text:'base预售活动不同状态的多语显示和购买', checked: false, category: '主题' },
    {text:'base预售倒计时显示', checked: false, category: '主题' },
    {text:'base预售视频播放正常', checked: false, category: '主题' },
    {text:'mb活动多语显示和购买', checked: false, category: '主题' },
    {text:'mb视频播放正常', checked: false, category: '主题' },
    {text:'三合一倒计时时间', checked: false, category: '主题' },
    {text:'三合一活动多语显示和完成情况', checked: false, category: '主题' },
    {text:'三合一奖励兑换', checked: false, category: '主题' },
    {text:'newgame新机台多语显示', checked: false, category: '主题' },
    {text:'newgame视频播放正常', checked: false, category: '主题' },
    {text:'mega77倒计时显示', checked: false, category: '主题' },
    {text:'mega77未完成状态多语显示', checked: false, category: '主题' },
    {text:'mega77完成状态多语显示', checked: false, category: '主题' },
    {text:'mega77完成的弹窗奖励显示', checked: false, category: '主题' },
    {text:'badge多语显示和完成情况', checked: false, category: '主题' },
    {text:'游戏和主题loading多语显示', checked: false, category: '主题' },
    {text:'comming多语显示', checked: false, category: '主题' },
    {text:'新主题BC显示和完成情况', checked: false, category: '主题' },
    {text:'新主题GM多语显示和购买', checked: false, category: '主题' },
    {text:'新主题玩法高低级房第二货币额外消耗', checked: false, category: '主题' },
    {text:'game rule描述，pay值和JP倍数显示正确，多语链接跳转正常', checked: false, category: '主题' },
    {text:'主题活动界面各按钮跳转', checked: false, category: '主题' },
    {text:'新主题GM购买后GM功能正常', checked: false, category: '主题' },
    {text:'主题皮肤显示', checked: false, category: '主题' },
    {text:'主题大厅分类', checked: false, category: '主题' },
    {text:'高低级房选bet界面显示', checked: false, category: '主题' },
    {text:'主题大小icon多语显示', checked: false, category: '主题' },
 
 
]